### ISSUE TITLE
403 Forbidden when clicking monitored aircraft Alert List

### ISSUE THREAD

**Issue by kimfr** [sdr-enthusiasts/docker-planefence#210] opened 2024-11-13 11:08 UTC
In a newly deployed planefence container - when I click on the monitored aircraft Alert List - I get a 403 Forbidden.

Looking at the link via the page http://<ip>:8088/plane-alert/ - I can see it points to http://<ip>:8088/plane-alert/alertlist.txt

Looking inside the planefence container, I get:
```
# find / -name alertlist.txt
/usr/share/planefence/html/plane-alert/alertlist.txt
/usr/share/plane-alert/html/alertlist.txt

# ls -la /usr/share/planefence/html/plane-alert/alertlist.txt
lrwxrwxrwx 1 root root 58 Nov 13 12:34 /usr/share/planefence/html/plane-alert/alertlist.txt -> /usr/share/planefence/persist/.internal/plane-alert-db.txt

# ls -la /usr/share/planefence/persist/.internal/plane-alert-db.txt
-rw-r--r-- 1 root root 3767636 Nov 13 12:34 /usr/share/planefence/persist/.internal/plane-alert-db.txt

# ls -la /usr/share/plane-alert/html/alertlist.txt
-rw-r--r-- 1 root root 10545 Aug 16 22:17 /usr/share/plane-alert/html/alertlist.txt

```
Both files can be read from within the planefence container:
```
tail -n1 /usr/share/planefence/html/plane-alert/alertlist.txt
E940FB,FAB-002,Gov of Bolivia,Dassault Falcon 50,FA50,Gov,Government,Must Be Nice,Free And Fair Elections,Dictator Alert,https://w.wiki/B3LJ,https://cdn.jetphotos.com/full/6/55153_1575059321.jpg,https://cdn.jetphotos.com/full/5/83758_1487098979.jpg,https://cdn.jetphotos.com/full/5/17432_1487090281.jpg,

tail -n1 /usr/share/plane-alert/html/alertlist.txt           
A2B2D2,N273NE,NE Life Flight,EuroCopter 45
```
I'm also a little confused as to why there are 2 different files?

**Comment by kimfr** [comment] 2024-11-13 16:35
It's NOT the plane-alert-db.txt that's the issue, it's working fine  - it's when built in "alertlist.txt" - ie. the list of used for Plane-Alert.

**Comment by kimfr** [comment] 2024-11-14 08:12
Left it running overnight and this morning it has now picked up 2 aircrafts so the list is being read and used - but when I click on the "list of monitored aircraft" - I still get a 403 Forbidden.
![image](https://github.com/user-attachments/assets/8c5bc11f-d63c-45b4-83a7-b1ea4dacec74)
![image](https://github.com/user-attachments/assets/9e7f3880-f785-4528-b53f-b09e34c56752)

**Comment by kx1t** [comment] 2024-12-09 13:38
I've checked this, and I can't reproduce it. Closing this issue for now; if it appears again, feel free to reopen

**Comment by jj358mhz** [comment] 2024-12-12 16:27
I can reproduce it
<img width="1904" alt="image" src="https://github.com/user-attachments/assets/8303e25b-4782-43ab-bd50-93f83eda514f" />

**Comment by kx1t** [comment] 2024-12-17 09:49
I’ll look into it some more

**Closed** 2024-12-17 10:27 UTC
